.github/workflows/helm-ci.yml

Required in order to upload SARIF reports to GitHub

Add missing `security-events` permission

---

charts/dependency-track/Chart.yaml
charts/dependency-track/templates/frontend/deployment.yaml

For the ENV variables to work, config.json must be writable on the filesystem.
This is because [30-oidc-configruation.sh](https://github.com/DependencyTrack/frontend/blob/master/docker/docker-entrypoint.d/30-oidc-configuration.sh) writes to this file to set the configuration. Without this change, the ENV configuration is ignored.

Disable readOnlyRootFilesystem for config.json ENV vars

---

.github/release.yml
.github/workflows/helm-release.yml
cr.yaml

Currently, the release description only contains the description of the Chart being released, which is not helpful at all for users.
Use the GitHub-generated release notes instead.

Generate release notes

---

charts/dependency-track/Chart.yaml
charts/dependency-track/README.md

When the value from Values.ingress.hostname, such as 'example.com', is used, the frontend attempts to send requests to 'example.com/example.com/api/...'.

Do not use `ingress.hostname` for `frontend.apiBaseUrl`

---

charts/dependency-track/Chart.yaml
charts/dependency-track/templates/extra-manifests.yaml
charts/dependency-track/templates/ingress.yaml
charts/dependency-track/values.yaml

Support `ingressClassName`, ingress `tls`, and `extraObjects`

---

charts/dependency-track/Chart.yaml
charts/dependency-track/templates/api-server/statefulset.yaml
charts/dependency-track/templates/frontend/deployment.yaml
charts/dependency-track/values.yaml

🛠 Helm Chart Enhancement
- Adds `nodeSelector` label to helm chart
🧪 How to Test
Deploy and Validate: Deploy the updated chart in a controlled environment. Validate all new functionalities. This change is non-breaking and backwards compatible.
Closes https://github.com/DependencyTrack/helm-charts/issues/40

add node-selector to helm chart

---

charts/dependency-track/Chart.yaml
charts/dependency-track/values.yaml

Also removes the default override for `frontend.image.tag`, now that API server and frontend both use the same version.

Bump `appVersion` to `4.11.0`

---

charts/dependency-track/Chart.yaml
charts/dependency-track/ci/multi-line-annotations.yaml
charts/dependency-track/templates/api-server/service.yaml
charts/dependency-track/templates/frontend/service.yaml

Fix #56 for service annotations across multiple lines.

Fix multi line annotations at services

---

ct.yaml

We don't trigger a release for every push to `main`, and it's a non-obvious requirement to contributors which just adds friction.
We'll manually bump the version prior to release.

Disable version increment check

---

charts/dependency-track/Chart.yaml
charts/dependency-track/README.md
charts/dependency-track/ci/additional-pvc.yaml
charts/dependency-track/ci/init-values.yaml
charts/dependency-track/ci/pvc-values.yaml
charts/dependency-track/ci/test-values.yaml
charts/dependency-track/templates/api-server/statefulset.yaml
charts/dependency-track/templates/frontend/deployment.yaml
charts/dependency-track/values-minikube.yaml
charts/dependency-track/values.yaml

We might have values defined in custom secrets/configmaps This change enables this capability
Related issue #82

Specify `envFrom` as `array` instead of `object` to support `valueFrom`

---

charts/dependency-track/values.schema.json

The schema only validates field types on a very basic level. It should suffice though to prevent people from blindly running into breaking changes, such as #83
Closes #69

Add JSON schema for `values.yaml`

---

charts/hyades/ci/test-values.yaml

This is still a temporary solution for until the services are able to set up topics on their own (https://github.com/DependencyTrack/hyades/issues/1195).
For the moment we just want to reduce duplication.

Use `create-topics.sh` script from `hyades` repository

---

charts/hyades/ci/test-values.yaml
charts/hyades/values-minikube.yaml

This makes it easier to kick the tires with the `hyades` chart. Previously, running PostgreSQL and Kafka via Docker Compose was required.

Add PostgreSQL and Redpanda to `values-minikube.yaml`

---

charts/dependency-track/README.md
charts/dependency-track/templates/_helpers.tpl
charts/dependency-track/values.yaml

Allow the common image registry to be overridden.
Because of the use of internal CAs, I need to rebuild the api server image.
Thus, it ends up in a different registry than the frontend image (which I don’t need to touch).
This PR enables the image registry to be changed for the api server and frontend independently and keeps the registry set in `.Values.common.image.registry` as default.
Known limitations:
Someone else might find it useful to also define per image pull secrets. I did not implement this, because I don’t have a good way to test it.

Add registry override to apiServer and frontend

---

charts/hyades/templates/api-server/deployment.yaml
charts/hyades/templates/mirror-service/deployment.yaml
charts/hyades/templates/notification-publisher/deployment.yaml
charts/hyades/templates/repo-meta-analyzer/deployment.yaml
charts/hyades/templates/vuln-analyzer/statefulset.yaml

Creation of Kafka Streams repartition topics currently fails with Unknown topic config name: prefix, when using Apache Kafka instead of Redpanda.
Rename the prefix config to avoid the error.
Issue: https://github.com/DependencyTrack/hyades/issues/1392

Rename kafka topic prefix config for apache kafka compatibility

---

charts/dependency-track/templates/api-server/deployment.yaml
charts/dependency-track/templates/api-server/statefulset.yaml
charts/dependency-track/values.schema.json
charts/dependency-track/values.yaml

Adding podSecurityContext should fix the permissions for the volume:
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod

Add default `podSecurityContext` to fix `/data` volume permissions

---

charts/dependency-track/templates/api-server/deployment.yaml

Right now, `data` volume doesn't get defined in the deployment manifest regardless of the value of `.Values.apiServer.persistentVolume.enabled`. 
The PR fixes this volume config.

Fix persistent volume in deployment manifest

---

charts/hyades/values.yaml

Due to various efficiency improvements we made in the recent past, API server instances no longer need as much memory. Also, increased memory requirements can now be addressed by spawning more replicas.
`requests.memory` and `limits.memory` are set to the same value, in order to lower the chances of pods getting `OOMKilled`. See https://xebia.com/blog/guide-kubernetes-jvm-integration/ for reference.

Lower default hyades API server memory request and limit to 2Gi

---

charts/dependency-track/Chart.yaml
charts/dependency-track/templates/_helpers.tpl
charts/dependency-track/values.yaml
charts/hyades/Chart.yaml
charts/hyades/templates/_helpers.tpl
charts/hyades/values.yaml

Allows image tags to be specified as `sha256` digest.
To avoid any formatting or length constraint issues, always use the chart's `appVersion` to the `app.kubernetes.io/version` label.
Fixes #111

Allow image tags to be specified as `sha256` digest

---

charts/dependency-track/templates/api-server/deployment.yaml
charts/dependency-track/templates/api-server/statefulset.yaml
charts/dependency-track/templates/frontend/deployment.yaml
charts/dependency-track/values.yaml
charts/hyades/templates/api-server/deployment.yaml
charts/hyades/templates/frontend/deployment.yaml
charts/hyades/templates/mirror-service/deployment.yaml
charts/hyades/templates/notification-publisher/deployment.yaml
charts/hyades/templates/repo-meta-analyzer/deployment.yaml
charts/hyades/templates/vuln-analyzer/deployment.yaml
charts/hyades/templates/vuln-analyzer/statefulset.yaml
charts/hyades/values.yaml
ct.yaml

Allows users to tailor the context to their organization's needs.

Make container `securityContext` configurable

---

charts/hyades/ci/test-initializer-values.yaml
charts/hyades/ci/test-vulnanalyzer-statefulset-values.yaml
charts/hyades/templates/_helpers.tpl
charts/hyades/templates/api-server/deployment.yaml
charts/hyades/templates/initializer/job.yaml
charts/hyades/templates/initializer/role.yaml
charts/hyades/templates/initializer/rolebinding.yaml
charts/hyades/templates/mirror-service/deployment.yaml
charts/hyades/templates/notification-publisher/deployment.yaml
charts/hyades/templates/repo-meta-analyzer/deployment.yaml
charts/hyades/templates/vuln-analyzer/deployment.yaml
charts/hyades/templates/vuln-analyzer/statefulset.yaml
charts/hyades/values.schema.json
charts/hyades/values.yaml

Introduces a `Job` that executes in the `post-install` and `post-upgrade` phases of a Helm deployment. The job executes initialization tasks and exits.
Pods that depend on successful execution of the job will wait for it, using new init containers. Since this waiting requires interacting with the Kubernetes API, pods will need `get`, `list`, and `watch` permissions on the `batch/jobs` resource. Creation of a `Role` with those permissions can be enabled.
This new functionality is disabled by default for now. The plan is to enable it per default once it's thoroughly tested, and we are confident it's the best way forward.
Depends on https://github.com/DependencyTrack/hyades-apiserver/pull/873
Closes #136

Add initializer job for hyades

---

charts/dependency-track/templates/ingress.yaml

- Add support for the /health endpoint introduced in version 4.8.0+ (https://docs.dependencytrack.org/getting-started/monitoring/)
- Because of the current ingress configuration the */health* endpoint will direct traffic to the frontend which will return a *404 Not found* whereas the api-server should handle the route
- Apply helm chart with ingress enabled
Note: I already tested on an dependency track deployment running on openshift (chart version 0.15.0) by simply adding:
(note that dtrack-dev is the deployment name I used)
```
- path: /health
pathType: Prefix
backend:
service:
name: dtrack-dev-dependency-track-api-server
port:
name: web
```
On GET \health I know properly get:
{"status":"UP","checks":[{"name":"database","status":"UP","data":{"nontx_connection_pool":"UP","tx_connection_po …

Add /health endpoint support when using ingress

---

charts/hyades/templates/api-server/deployment.yaml
charts/hyades/templates/frontend/deployment.yaml
charts/hyades/templates/mirror-service/deployment.yaml
charts/hyades/templates/notification-publisher/deployment.yaml
charts/hyades/templates/repo-meta-analyzer/deployment.yaml
charts/hyades/templates/vuln-analyzer/deployment.yaml
charts/hyades/values.schema.json
charts/hyades/values.yaml

For Kafka consumers, it can be desirable to *not* do `RollingUpdate`s in order to prevent repetetive rebalances. Since those services are not user-facing anyway, there's no downtime involved in following a `Recreate` strategy instead.

Make deployment strategy of hyades services configurable

---

charts/dependency-track/README.md
charts/dependency-track/templates/api-server/deployment.yaml
charts/dependency-track/templates/api-server/statefulset.yaml
charts/dependency-track/templates/frontend/deployment.yaml
charts/dependency-track/values.schema.json
charts/dependency-track/values.yaml

#32
Creates `extraPodLabels` so that a user can set specific pod labels in either the `apiServer` or `frontend` deployment.

Support extraPodLabels in apiServer and Frontend

---

charts/dependency-track/templates/api-server/servicemonitor.yaml

Fixes #170
As per [this](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#endpoint) documentation, the API endpoint `timeout` does not exist and should be `scrapeTimeout`.

Fix .Values.apiServer.serviceMonitor.scrapeTimeout

---

charts/dependency-track/README.md
charts/dependency-track/templates/api-server/servicemonitor.yaml
charts/dependency-track/values.yaml

- Fixed the wording for interval (`scrapeInternal` -> `scrapeInterval`).
- Increased the default value for `scrapeInterval` now that `scrapeTimeout` is fixed (https://github.com/DependencyTrack/helm-charts/pull/171) because it makes the service monitor invalid (`ServiceMonitor dependencytrack-api-server was rejected due to invalid configuration: scrapeTimeout "30s" greater than scrapeInterval "15s"`).

Fix default values and naming for scrape interval

---

charts/hyades/templates/api-server/deployment.yaml
charts/hyades/templates/api-server/hpa.yaml
charts/hyades/templates/frontend/deployment.yaml
charts/hyades/templates/frontend/hpa.yaml
charts/hyades/templates/mirror-service/deployment.yaml
charts/hyades/templates/notification-publisher/deployment.yaml
charts/hyades/templates/notification-publisher/hpa.yaml
charts/hyades/templates/repo-meta-analyzer/deployment.yaml
charts/hyades/templates/repo-meta-analyzer/hpa.yaml
charts/hyades/templates/vuln-analyzer/deployment.yaml
charts/hyades/templates/vuln-analyzer/hpa.yaml
charts/hyades/templates/vuln-analyzer/statefulset.yaml
charts/hyades/values.yaml

Enable turning off/on the `replica` and `strategy.type` fields in deployment manifests so that HPAs can be configured for Hyades

Update to allow HPA configuration

---

charts/dependency-track/templates/api-server/deployment.yaml
charts/dependency-track/templates/frontend/deployment.yaml

According to the Kubernetes [documentation](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/) the service account should be referenced via `serviceAccountName`

`serviceAccount` -> `serviceAccountName`

---

charts/dependency-track/templates/api-server/deployment.yaml

The template for the API deployment didn't include additional volumes even if you declare them in the respective part of the values.yaml file. This PR adds the missing templating so additional volumes can now be attached.

Additional volumes didnt get attached properly to deployment

---

charts/dependency-track/README.md
charts/dependency-track/ci/test-values.yaml
charts/dependency-track/templates/api-server/deployment.yaml
charts/dependency-track/templates/api-server/statefulset.yaml
charts/dependency-track/values.schema.json
charts/dependency-track/values.yaml

This change adds a new configuration option `apiServer.metrics.enabled` (boolean, defaults to `true`) that controls whether Prometheus scraping annotations are applied to the API server pods.
This gives users more control over their monitoring setup and allows them to disable Prometheus metrics collection if needed.
Closes #228

feat(apiServer): add ability to disable Prometheus metrics scraping

---

charts/dependency-track/templates/api-server/deployment.yaml
charts/dependency-track/templates/api-server/statefulset.yaml
charts/dependency-track/templates/frontend/deployment.yaml
charts/dependency-track/values.schema.json
charts/dependency-track/values.yaml

This feature allows disabling Kubernetes service links, because the frontend fails to start on large Kubernetes namespaces with a lot of services (~ 375) with the message:
```
/docker-entrypoint.d/20-envsubst-on-templates.sh: line 53: envsubst: Argument list too long
```
To disable service links, add this to your `values.yaml`:
```yaml
common:
serviceLinks: false
```
The documentation (https://kubernetes.io/docs/tutorials/services/connect-applications-service/) states:
> If the service environment variables are not desired (because possible clashing with expected program ones, too many variables to process, only using DNS, etc) you can disable this mode by setting the enableServiceLinks flag to false on the pod spec.

Allow disabling service links
